/*
 * Generated by XDoclet - Do not edit!
 */
package org.dentaku.foundation.connector.ejb;

/**
 * Local home interface for EJBConnector.
 * @clover ///CLOVER:OFF
 */
public interface EJBConnectorLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/EJBConnectorLocal";
   public static final String JNDI_NAME="EJBConnectorLocal";

   public org.dentaku.foundation.connector.ejb.EJBConnectorLocal create()
      throws javax.ejb.CreateException;

}
