/*
 * Generated by XDoclet - Do not edit!
 */
package org.dentaku.foundation.connector.ejb;

/**
 * Home interface for EJBConnector.
 * @clover ///CLOVER:OFF
 */
public interface EJBConnectorHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/EJBConnector";
   public static final String JNDI_NAME="connector/bill2/EJBConnector";

   public org.dentaku.foundation.connector.ejb.EJBConnector create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
